version: "3"

services:
  go-application-service:
    container_name: go-xml-container
    image: go-xml:v1.0.3
    build:
      context: ./go-app
      dockerfile: Imagefile
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    volumes:
      - ./go-app:/usr/app/:cached

  go-application-sidecar-service:
    container_name: go-sidecar
    image: json-sidecar:v1.0.3
    build:
      context: ./node-negotiator-sidecar
      dockerfile: Imagefile
    environment:
      - PORT=8082
      - MAIN_PROCESS=go-application-service
      - MAIN_PROCESS_PORT=8081
    ports:
      - 8082:8082
    depends_on:
      - go-application-service
    volumes:
      - ./node-negotiator-sidecar/src:/usr/app/src

  node-application-service:
    container_name: node-xml-container
    image: node-xml:v1.0.3
    build:
      context: ./node-app
      dockerfile: Imagefile
    environment:
      - PORT=8083
    ports:
      - 8083:8083
    volumes:
      - ./node-app/src:/usr/app/src:cached

  node-application-sidecar-service:
    container_name: node-sidecar
    image: json-sidecar:v1.0.3
    build:
      context: ./node-negotiator-sidecar
      dockerfile: Imagefile
    environment:
      - PORT=8084
      - MAIN_PROCESS=node-application-service
      - MAIN_PROCESS_PORT=8083
    ports:
      - 8084:8084
    depends_on:
      - node-application-service
    volumes:
      - ./node-negotiator-sidecar/src:/usr/app/src

  python-application-service:
    container_name: python-xml-container
    image: python-xml:v1.0.3
    build:
      context: ./python-app
      dockerfile: Imagefile
    environment:
      - PORT=8085
    ports:
      - 8085:8085
    volumes:
      - ./python-app/src:/usr/app/src:cached

  python-application-sidecar-service:
    container_name: python-sidecar
    image: json-sidecar:v1.0.3
    build:
      context: ./node-negotiator-sidecar
      dockerfile: Imagefile
    environment:
      - PORT=8086
      - MAIN_PROCESS=python-application-service
      - MAIN_PROCESS_PORT=8085
    ports:
      - 8086:8086
    depends_on:
      - python-application-service
    volumes:
      - ./node-negotiator-sidecar/src:/usr/app/src
