version: "3"

services:
  node-application-service:
    container_name: node-xml-container
    image: node-xml:v1.0.3
    build:
      context: .
      dockerfile: Imagefile
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/app/src
